# Generated by Django 4.1.7 on 2023-03-18 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='studentID',
            field=models.IntegerField(unique=True),
        ),
    ]
