# Generated by Django 4.1.7 on 2023-03-18 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_users_studentid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Ticket_Requests',
        ),
    ]
